services:
  db:
    image: mysql:8.0
    container_name: mysqlAvancado
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
